// <auto-generated />
using FullStack.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullStack.Data.Migrations
{
    [DbContext(typeof(FullStackDbContext))]
    [Migration("20210406113807_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FullStack.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AdminRole")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AdminRole = true,
                            Email = "properproperties1@gmail.com",
                            FirstName = "John",
                            LastName = "Smith",
                            Locked = false,
                            Password = "ppAdmin1"
                        },
                        new
                        {
                            Id = 3,
                            AdminRole = true,
                            Email = "properproperties2@gmail.com",
                            FirstName = "Johan",
                            LastName = "Smit",
                            Locked = false,
                            Password = "ppAdmin2"
                        },
                        new
                        {
                            Id = 1,
                            AdminRole = false,
                            Email = "regardtvisagie@gmail.com",
                            FirstName = "Regardt",
                            LastName = "Visagie",
                            Locked = false,
                            Password = "Reg14061465"
                        },
                        new
                        {
                            Id = 4,
                            AdminRole = false,
                            Email = "mk@yahoo.com",
                            FirstName = "Michelle",
                            LastName = "Koorts",
                            Locked = false,
                            Password = "Koorts123"
                        },
                        new
                        {
                            Id = 5,
                            AdminRole = false,
                            Email = "pieterj@yhotmail.com",
                            FirstName = "Pieter",
                            LastName = "Joubert",
                            Locked = false,
                            Password = "Jouba1987"
                        },
                        new
                        {
                            Id = 6,
                            AdminRole = false,
                            Email = "cs@ymail.com",
                            FirstName = "Chulu",
                            LastName = "Sibuzo",
                            Locked = false,
                            Password = "Chulu1982"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
